version: '3'

services:
  ui:
    image: ${IMAGE_UI}:${IMAGE_TAG}
    labels:
      - "traefik.http.routers.${REPOSITORY_NAME}${SUFFIX}.rule=PathPrefix(`/${REPOSITORY_NAME}${SUFFIX}`)"
    networks:
      - proxy
    environment:
      EXTRAPATH: '/${REPOSITORY_NAME}${SUFFIX}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      AWS_DEFAULT_REGION: '${AWS_DEFAULT_REGION}'
      OPENROUTESERVICE_API_KEY: '${OPENROUTESERVICE_API_KEY}'
      BING_API_KEY: '${BING_API_KEY}'

networks:
  proxy:
    external: true