name: Build, Test, Deploy

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  IMAGE_UI: ${{ secrets.ECR_URL }}/iads/${{ github.event.repository.name }}/ui
  IP_ADDRESS: ${{ secrets.IP_SAGEMAKER_NOTEBOOK_OMAR }}
  OPENROUTESERVICE_API_KEY: '${{ secrets.OPENROUTESERVICE_API_KEY }}'
  BING_API_KEY: '${{ secrets.BING_API_KEY }}'

jobs:
  aws_ecr:
    runs-on: sagemaker
    steps:
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

      - name: Create AWS ECR registry for UI if not existing
        run: aws ecr describe-repositories --repository-names iads/${REPOSITORY_NAME}/ui || aws ecr create-repository --repository-name iads/${REPOSITORY_NAME}/ui
      
  build_ui:
    runs-on: sagemaker
    needs: aws_ecr
    steps:
      - uses: actions/checkout@v3

      - name: Set Docker image tag
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            echo "IMAGE_TAG=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Build UI Docker image
        run: |
          cd ui
          docker build -f Dockerfile -t ${IMAGE_UI}:${{ env.IMAGE_TAG }} .
      - name: Push UI Docker image to AWS ECR registry
        run: docker push ${IMAGE_UI}:${{ env.IMAGE_TAG }}

  deploy_prod:
    runs-on: sagemaker
    needs: build_ui
    if: github.ref == 'refs/heads/main'
    env:
      SUFFIX: ""
      IMAGE_TAG: ${{ github.ref_name }}
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
    steps:
      - uses: actions/checkout@v3

      - name: Remove previous stack
        run: docker stack rm ${REPOSITORY_NAME}

      - name: Deploy new stack
        run: docker stack deploy -c docker-compose.yml ${REPOSITORY_NAME}

  deploy_dev:
    runs-on: sagemaker
    needs: build_ui
    if: github.event_name == 'pull_request'
    env:
      IMAGE_TAG: ${{ github.head_ref }}
      SUFFIX: "-${{ github.head_ref }}"
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
    steps:
      - uses: actions/checkout@v3

      - name: Remove previous stack
        run: docker stack rm ${REPOSITORY_NAME}${SUFFIX}

      - name: Deploy new stack
        run: docker stack deploy -c docker-compose.yml ${REPOSITORY_NAME}${SUFFIX}